// src/lib/blocks/footer/footer.svelte
<script lang="ts">
	// imports
	import { UContainer, UFooterLinks } from '$lib/index.js';
	import type { XDir } from '$lib/types/index.js';
	import type { Link } from '$lib/types/link.js';
	import { twJoin } from 'tailwind-merge';
	// props
	export let title: string = 'Centlax';
	export let dir: XDir = 'east';
	export let links: Link[] = [];
	let classProp: string | string[] = '';
	export { classProp as class };
	// config
	let year = new Date().getFullYear();
	const css = {
		wrapper: 'bg-white/50 dark:bg-gray-900/50 ',
		border: 'border-t border-gray-900/10 dark:border-white/10',
		base: 'mx-auto',
		grid: 'py-8 lg:py-12 xl:grid xl:grid-cols-3 xl:gap-8',
		east: 'space-y-8 text-gray-600 dark:text-gray-300 lg:mr-10',
		center: '',
		west: 'space-y-8 text-gray-600 dark:text-gray-300 lg:ml-10',
		notes: {
			base: 'py-2 lg:py-4 ',
			year: 'text-sm leading-5 text-gray-600/80 dark:text-gray-300/80'
		}
	};
	// reactive
	$: full = $$slots.default || links.length;
</script>

<footer class={twJoin(css.wrapper, css.border, classProp)} aria-labelledby="footer-heading">
	<UContainer>
		<h2 id="footer-heading" class="sr-only">Footer</h2>

		<div class={twJoin(css.base, !full && 'pt-1')}>
			{#if full}
				<div class={css.grid}>
					{#if $$slots.default && dir === 'east'}
						<div class={css.east}>
							<slot />
						</div>
					{/if}
					<slot name="links">
						<UFooterLinks {links} />
					</slot>
					{#if $$slots.default && dir === 'west'}
						<div class={css.west}>
							<slot />
						</div>
					{/if}
				</div>
			{/if}
			<div class="{css.notes.base} {full && css.border}">
				<p class={css.notes.year}>
					{title} &copy; {year}
				</p>
				<slot name="notes" />
			</div>
		</div>
	</UContainer>
</footer>

// components/layouts/footer/Footer.vue
<template>
  <footer v-bind="props" :class="[ui.wrapper]">
    <div v-if="$slots.default">
      <slot />
    </div>
    <div :class="[ui.notice.font, ui.notice.primary]">
      <span class="flex flex-wrap gap-x-1 justify-center">
        <NuxtLink :to="props.to" :class="['hover:underline']"> Centlax</NuxtLink>
        &copy; {{ new Date().getFullYear() }}
      </span>
      <slot v-if="props.notice?.length" name="notice">
        <NuxtLink v-for="(item, index) in props.notice" :key="index" :to="props.to">
          {{ item.label }}
        </NuxtLink>
      </slot>
    </div>
    <div v-if="$slots.social">
      <slot name="social" />
    </div>
  </footer>
</template>

<script setup lang="ts">
import type { Link } from '#ui/types'

const props = withDefaults(defineProps<{
  to?: string
  title?: string
  notice?: Link[]
  class?: any
}>(), {
  to: 'https://centlax.com',
  title: undefined,
  notice: () => [],
  size: 'md',
  class: undefined
})

const ui = {
  wrapper: 'py-2 bg-white/90 dark:bg-gray-900/90',
  font: 'text-sm',
  notice: {
    font: 'text-sm',
    primary: 'text-primary-600/90 dark:text-primary-500/90'
  }
}
</script>
