// src/lib/components/elements/button/button.svelte
<script lang="ts">
	// imports
	import type { HTMLAnchorAttributes, HTMLButtonAttributes } from 'svelte/elements';
	import type { ButtonProps } from './button.props.js';
	import { css } from './button.styles.js';
	import { UIcon } from '$lib/index.js';
	import { twJoin } from 'tailwind-merge';
	import { ui } from '$lib/ui.config.js';

	// types
	type $$Props = (HTMLAnchorAttributes & ButtonProps) | (HTMLButtonAttributes & ButtonProps);

	// props
	let classProp: string | undefined | null = '';
	export { classProp as class };
	export let href: ButtonProps['href'] = '';
	export let icon: ButtonProps['icon'] = '';
	export let label: ButtonProps['label'] = '';
	export let truncate: ButtonProps['truncate'] = false;
	export let square: ButtonProps['square'] = false;
	export let block: ButtonProps['block'] = false;
	export let size: ButtonProps['size'] = ui.size;
	export let loading: ButtonProps['loading'] = false;
	export let padded: ButtonProps['padded'] = true;
	export let leading: ButtonProps['leading'] = false;
	export let trailing: ButtonProps['trailing'] = false;
	export let rounded: ButtonProps['rounded'] = false;
	export let variant: ButtonProps['variant'] = 'solid';
	export let color: ButtonProps['color'] = 'primary';

	// reactive
	$: isLeading =
		(icon && leading) ||
		(icon && !trailing) ||
		(loading && !trailing) ||
		(typeof icon === 'object' && icon.leading);

	$: isTrailing =
		(icon && trailing) || (loading && trailing) || (typeof icon === 'object' && icon.trailing);

	$: isSquare = square || (!$$slots.default && !label);

	$: loadingIcon = typeof icon === 'object' && icon.loading ? icon.loading : ui.icon.loading;
	$: leadingIcon = loading ? loadingIcon : typeof icon === 'object' ? icon.leading : icon;
	$: trailingIcon =
		loading && !isLeading ? loadingIcon : typeof icon === 'object' ? icon.trailing : icon;

	// config
	let _variant: string =
		//@ts-ignore
		css.variant?.base[variant]?.[color] ||
		//@ts-ignore
		css.variant?.mask[variant].replaceAll('{color}', color);

	// reactive
	$: buttonCSS = twJoin(
		css.base,
		css.font,
		_variant,
		css.gap[size || 'sm'],
		css.text[size || 'sm'],
		block ? css.block : css.inline,
		padded && css.padding[isSquare ? 'square' : 'rectangle'][size || 'sm'],
		rounded ? 'rounded-full' : css.rounded,
		classProp
	);
	$: leadingIconCSS = twJoin(loading ? `${loadingIcon} animate-spin` : leadingIcon);
	$: trailingIconCSS = twJoin(loading ? `${loadingIcon} animate-spin` : trailingIcon);
</script>

<!-- svelte-ignore a11y-no-static-element-interactions -->
<svelte:element
	this={href ? 'a' : 'button'}
	on:click
	on:change
	on:keydown
	on:keyup
	on:mouseenter
	on:mouseleave
	class={buttonCSS}
	{...$$restProps}
>
	{#if $$slots.leading || leadingIcon}
		<slot name="leading">
			<UIcon name={leadingIconCSS} aria-hidden="true" />
		</slot>
	{/if}
	<slot>
		<span class={truncate ? css.truncate : ''}>
			{label}
		</span>
	</slot>
	{#if $$slots.trailing || trailingIcon}
		<slot name="trailing">
			{#if isTrailing}
			<UIcon name={trailingIconCSS} aria-hidden="true" />
			{/if}
		</slot>
	{/if}
</svelte:element>

// components/elements/button/Button.vue
<template>
  <ULink
    :to="props.to"
    :primary="false"
    type="button"
    :disabled="disabled || loading"
    :class="buttonUI"
    v-bind="$attrs"
  >
    <slot name="leading" :disabled="disabled" :loading="loading">
      <UIcon v-if="leadingIcon" :name="leadingIcon" :class="leadingIconUI" aria-hidden="true" />
    </slot>

    <slot>
      <span v-if="label" :class="[truncate ? ui.truncate : '']"> {{ props.label }} </span>
    </slot>

    <slot name="trailing" :disabled="disabled">
      <UIcon
        v-if="props.trailingIcon"
        :name="props.trailingIcon"
        :class="trailingIconUI"
        aria-hidden="true"
      />
    </slot>
  </ULink>
</template>

<script setup lang="ts">
import { computed } from 'vue'
import { twMerge, twJoin } from 'tailwind-merge'
import { UIcon, ULink } from '#components'
import ui from './button.css'
import type { Button } from '#ui/types/button'
const slots = useSlots()

defineOptions({
  inheritAttrs: false
})

const props = withDefaults(defineProps<Button>(), {
  to: undefined,
  label: undefined,
  block: false,
  loading: false,
  disabled: false,
  padded: true,
  square: false,
  truncate: false,
  iconColor: false,
  icon: null,
  trailingIcon: null,
  size: 'md',
  color: 'primary',
  variant: 'solid',
  loadingIcon: 'heroicons:arrow-path-20-solid',
  class: ''
})

const isSquare = computed(() => props.square || (!slots.default && !props.label))
const buttonUI = computed(() => {
  return twMerge(twJoin(
    ui.base, ui.font,
    ui.rounded[props.size],
    ui.text[props.size],
    ui.gap[props.size],
    props.padded && ui[isSquare.value ? 'square' : 'padding'][props.size],
    isWhiteGray(props.color) && ui.color[props.color],
    !isWhiteGray(props.color) && ui.variant[props.variant].replaceAll('{color}', props.color),
    props.block ? ui.block : ui.inline
  ), props.class)
})

const leadingIcon = computed(() => {
  return props.loading ? ui.default.loadingIcon : props.icon
})

const leadingIconUI = computed(() => {
  return twJoin(
    ui.icon.base,
    ui.icon.size[props.size],
    props.iconColor && isWhiteGray(props.color) && ui.icon.color,
    props.loading && ui.icon.loading
  )
})

const trailingIconUI = computed(() => {
  return twJoin(
    ui.icon.base,
    ui.icon.size[props.size],
    props.loading && ui.icon.loading
  )
})
</script>
