// src/lib/components/navigations/header/header.svelte
<script lang="ts">
	import { UButton, UColorMode, ULogo } from '$lib/index.js';
	import { twJoin } from 'tailwind-merge';
	export let title: string = 'Centlax';

	const css = {
		base: 'mx-auto text-gray-900 dark:text-white bg-white dark:bg-gray-900',
		fixed: 'sticky top-0 z-100 backdrop-blur-md',
	};
	$:headerCSS = twJoin(css.base, css.fixed);
</script>
<header class={headerCSS}>
	<nav class="flex items-center justify-between gap-x-6 py-2" aria-label="Global">
		<div class="flex lg:flex-1">
			<slot name="east">
				<a href="/" class="-ml-1 flex items-center gap-1">
					<span class="sr-only">Centlax</span>
					<slot name="logo">
						<ULogo />
					</slot>
					<span class="font-medium text-xl">{title}</span>
				</a>
			</slot>
		</div>
		<div class="hidden lg:flex lg:gap-x-12">
			<slot />
		</div>
		<div class="flex flex-1 items-center justify-end gap-x-6">
			<slot name="west">
				<UButton variant="ghost" color="white" label="Log in" href="/" />
				<UButton label="Sign up" href="/" />
				<UColorMode />
			</slot>
		</div>
	</nav>
</header>

// src/runtime/customs/blocks/header/Header.vue
<template>
  <header ref="el" :class="ui.wrapper" aria-label="Global">
    <div ref="left" class="flex justify-center items-center lg:flex-1">
      <ULogo class="dark:fill-white h-9" />
      <span class="ml-2 font-semibold text-2xl tracking-widest">Centlax</span>
    </div>
    <div ref="left" class="flex h-6 w-full" />

    <div class="flex gap-x-6 lg:gap-x-12 text-gray-900 dark:text-white text-sm font-semibold leading-6">
      <slot />
    </div>

    <div class="lg:flex lg:flex-1 lg:justify-end">
      <slot name="left" />
    </div>

    <div class="">
      <UButton square color="white" icon="i-fluent-navigation-24-regular">
        <span class="sr-only">Open main menu</span>
      </UButton>
    </div>
  </header>
</template>

<script setup lang="ts">
import ui from './header.css'
import UButton from '../../../components/elements/Button.vue'
import ULogo from '../../elements/logo/Logo.vue'
</script>

<style>
</style>
