// components/layout/Card.vue
<template>
  <component
    :is="$attrs.onSubmit ? 'form' : as"
    :class="cardUI"
    v-bind="$attrs"
  >
    <div v-if="$slots.header" :class="[ui.header.base, ui.header.padding, ui.header.background]">
      <slot name="header" />
    </div>
    <div :class="[ui.body.base, ui.body.padding, ui.body.background]">
      <slot />
    </div>
    <div v-if="$slots.footer" :class="[ui.footer.base, ui.footer.padding, ui.footer.background]">
      <slot name="footer" />
    </div>
  </component>
</template>

<script setup lang="ts">
import { computed } from 'vue'
import type { PropType } from 'vue'
import { twMerge, twJoin } from 'tailwind-merge'
defineOptions({
  inheritAttrs: false
})

const props = defineProps({
  as: {
    type: String,
    default: 'div'
  },
  class: {
    type: [String, Object, Array] as PropType<any>,
    default: () => ''
  }
})

const ui = {
  base: 'overflow-hidden',
  background: 'bg-white dark:bg-gray-900',
  divide: 'divide-y divide-gray-200 dark:divide-gray-800',
  ring: 'ring-1 ring-gray-200 dark:ring-gray-800',
  rounded: 'rounded-lg',
  shadow: 'shadow',
  body: {
    base: '',
    background: '',
    padding: 'px-4 py-5 sm:p-6'
  },
  header: {
    base: '',
    background: '',
    padding: 'px-4 py-5 sm:px-6'
  },
  footer: {
    base: '',
    background: '',
    padding: 'px-4 py-4 sm:px-6'
  }
}

const cardUI = computed(() => {
  return twMerge(twJoin(
    ui.base,
    ui.rounded,
    ui.divide,
    ui.ring,
    ui.shadow,
    ui.background
  ), props.class)
})
</script>

// src/lib/components/layouts/card/card.svelte
<script lang="ts">
	import { twMerge } from 'tailwind-merge';

	export let as: string = 'div';
	export let rounded: boolean = true;
	let cardUI: string = '';
	export { cardUI as class };
	export let northUI: string = '';
	export let centerUI: string = '';
	export let southUI: string = '';
	const css = {
		base: '',
		background: 'bg-white dark:bg-gray-900',
		divide: 'divide-y divide-gray-200 dark:divide-gray-800',
		ring: 'ring-1 ring-gray-200 dark:ring-gray-800',
		rounded: 'rounded-lg',
		shadow: 'shadow',
		center: {
			base: '',
			background: '',
			padding: 'px-4 py-5 sm:p-6'
		},
		north: {
			base: '',
			background: '',
			padding: 'px-4 py-5 sm:px-6'
		},
		south: {
			base: '',
			background: '',
			padding: 'px-4 py-4 sm:px-6'
		}
	};
	$: cardCSS = twMerge(
		css.base,
		rounded && css.rounded,
		css.divide,
		css.ring,
		css.shadow,
		css.background,
		cardUI
	);

	$: northCSS = twMerge(css.north.base, css.north.padding, css.north.background, northUI);
	$: centerCSS = twMerge(css.center.base, css.center.padding, css.center.background, centerUI);
	$: southCSS = twMerge(css.south.base, css.south.padding, css.south.background, southUI);
</script>

<svelte:element this={as} class={cardCSS}>
	{#if $$slots.north}
		<div class={northCSS}>
			<slot name="north" />
		</div>
	{/if}
	<div class={centerCSS}>
		<slot />
	</div>
	{#if $$slots.south}
		<div class={southCSS}>
			<slot name="south" />
		</div>
	{/if}
</svelte:element>
