// src/lib/components/elements/button/button.svelte
<script lang="ts">
	// imports
	import type { HTMLAnchorAttributes, HTMLButtonAttributes } from 'svelte/elements';
	import type { ButtonProps } from './button.props.js';
	import { css } from './button.styles.js';
	import { UIcon } from '$lib/index.js';
	import { twJoin } from 'tailwind-merge';
	import { ui } from '$lib/ui.config.js';

	// types
	type $$Props = (HTMLAnchorAttributes & ButtonProps) | (HTMLButtonAttributes & ButtonProps);

	// props
	let classProp: string | undefined | null = '';
	export { classProp as class };
	export let href: ButtonProps['href'] = '';
	export let icon: ButtonProps['icon'] = '';
	export let label: ButtonProps['label'] = '';
	export let truncate: ButtonProps['truncate'] = false;
	export let square: ButtonProps['square'] = false;
	export let block: ButtonProps['block'] = false;
	export let size: ButtonProps['size'] = ui.size;
	export let loading: ButtonProps['loading'] = false;
	export let padded: ButtonProps['padded'] = true;
	export let leading: ButtonProps['leading'] = false;
	export let trailing: ButtonProps['trailing'] = false;
	export let rounded: ButtonProps['rounded'] = false;
	export let variant: ButtonProps['variant'] = 'solid';
	export let color: ButtonProps['color'] = 'primary';

	// reactive
	$: isLeading =
		(icon && leading) ||
		(icon && !trailing) ||
		(loading && !trailing) ||
		(typeof icon === 'object' && icon.leading);

	$: isTrailing =
		(icon && trailing) || (loading && trailing) || (typeof icon === 'object' && icon.trailing);

	$: isSquare = square || (!$$slots.default && !label);

	$: loadingIcon = typeof icon === 'object' && icon.loading ? icon.loading : ui.icon.loading;
	$: leadingIcon = loading ? loadingIcon : typeof icon === 'object' ? icon.leading : icon;
	$: trailingIcon =
		loading && !isLeading ? loadingIcon : typeof icon === 'object' ? icon.trailing : icon;

	// config
	let _variant: string =
		//@ts-ignore
		css.variant?.base[variant]?.[color] ||
		//@ts-ignore
		css.variant?.mask[variant].replaceAll('{color}', color);

	// reactive
	$: buttonCSS = twJoin(
		css.base,
		css.font,
		_variant,
		css.gap[size || 'sm'],
		css.text[size || 'sm'],
		block ? css.block : css.inline,
		padded && css.padding[isSquare ? 'square' : 'rectangle'][size || 'sm'],
		rounded ? 'rounded-full' : css.rounded,
		classProp
	);
	$: leadingIconCSS = twJoin(loading ? `${loadingIcon} animate-spin` : leadingIcon);
	$: trailingIconCSS = twJoin(loading ? `${loadingIcon} animate-spin` : trailingIcon);
</script>

<!-- svelte-ignore a11y-no-static-element-interactions -->
<svelte:element
	this={href ? 'a' : 'button'}
	on:click
	on:change
	on:keydown
	on:keyup
	on:mouseenter
	on:mouseleave
	class={buttonCSS}
	{...$$restProps}
>
	{#if $$slots.leading || leadingIcon}
		<slot name="leading">
			<UIcon name={leadingIconCSS} aria-hidden="true" />
		</slot>
	{/if}
	<slot>
		<span class={truncate ? css.truncate : ''}>
			{label}
		</span>
	</slot>
	{#if $$slots.trailing || trailingIcon}
		<slot name="trailing">
			{#if isTrailing}
			<UIcon name={trailingIconCSS} aria-hidden="true" />
			{/if}
		</slot>
	{/if}
</svelte:element>

// src/runtime/components/elements/Button.vue
<template>
  <ULink :type="type" :disabled="disabled || loading" :class="buttonClass" v-bind="attrs">
    <slot name="leading" :disabled="disabled" :loading="loading">
      <UIcon v-if="isLeading && leadingIconName" :name="leadingIconName" :class="leadingIconClass" aria-hidden="true" />
    </slot>

    <slot>
      <span v-if="label" :class="[truncate ? ui.truncate : '']">
        {{ label }}
      </span>
    </slot>

    <slot name="trailing" :disabled="disabled" :loading="loading">
      <UIcon v-if="isTrailing && trailingIconName" :name="trailingIconName" :class="trailingIconClass" aria-hidden="true" />
    </slot>
  </ULink>
</template>

<script lang="ts">
import { computed, defineComponent, toRef } from 'vue'
import type { PropType } from 'vue'
import { twMerge, twJoin } from 'tailwind-merge'
import UIcon from '../elements/Icon.vue'
import ULink from '../elements/Link.vue'
import { useUI } from '../../composables/useUI'
import { mergeConfig } from '../../utils'
import { useInjectButtonGroup } from '../../composables/useButtonGroup'
import type { ButtonColor, ButtonSize, ButtonVariant, Strategy } from '../../types'
// @ts-expect-error
import appConfig from '#build/app.config'
import { button } from '#ui/ui.config'

const config = mergeConfig<typeof button>(appConfig.ui.strategy, appConfig.ui.button, button)

export default defineComponent({
  components: {
    UIcon,
    ULink
  },
  inheritAttrs: false,
  props: {
    type: {
      type: String,
      default: 'button'
    },
    block: {
      type: Boolean,
      default: false
    },
    label: {
      type: String,
      default: null
    },
    loading: {
      type: Boolean,
      default: false
    },
    disabled: {
      type: Boolean,
      default: false
    },
    padded: {
      type: Boolean,
      default: true
    },
    size: {
      type: String as PropType<ButtonSize>,
      default: () => config.default.size,
      validator (value: string) {
        return Object.keys(config.size).includes(value)
      }
    },
    color: {
      type: String as PropType<ButtonColor>,
      default: () => config.default.color,
      validator (value: string) {
        return [...appConfig.ui.colors, ...Object.keys(config.color)].includes(value)
      }
    },
    variant: {
      type: String as PropType<ButtonVariant>,
      default: () => config.default.variant,
      validator (value: string) {
        return [
          ...Object.keys(config.variant),
          ...Object.values(config.color).flatMap(value => Object.keys(value))
        ].includes(value)
      }
    },
    icon: {
      type: String,
      default: null
    },
    loadingIcon: {
      type: String,
      default: () => config.default.loadingIcon
    },
    leadingIcon: {
      type: String,
      default: null
    },
    trailingIcon: {
      type: String,
      default: null
    },
    trailing: {
      type: Boolean,
      default: false
    },
    leading: {
      type: Boolean,
      default: false
    },
    square: {
      type: Boolean,
      default: false
    },
    truncate: {
      type: Boolean,
      default: false
    },
    class: {
      type: [String, Object, Array] as PropType<any>,
      default: () => ''
    },
    ui: {
      type: Object as PropType<Partial<typeof config> & { strategy?: Strategy }>,
      default: () => ({})
    }
  },
  setup (props, { slots }) {
    const { ui, attrs } = useUI('button', toRef(props, 'ui'), config)

    const { size, rounded } = useInjectButtonGroup({ ui, props })

    const isLeading = computed(() => {
      return (props.icon && props.leading) || (props.icon && !props.trailing) || (props.loading && !props.trailing) || props.leadingIcon
    })

    const isTrailing = computed(() => {
      return (props.icon && props.trailing) || (props.loading && props.trailing) || props.trailingIcon
    })

    const isSquare = computed(() => props.square || (!slots.default && !props.label))

    const buttonClass = computed(() => {
      const variant = ui.value.color?.[props.color as string]?.[props.variant as string] || ui.value.variant[props.variant]

      return twMerge(twJoin(
        ui.value.base,
        ui.value.font,
        rounded.value[size.value],
        ui.value.size[size.value],
        ui.value.gap[size.value],
        props.padded && ui.value[isSquare.value ? 'square' : 'padding'][size.value],
        variant?.replaceAll('{color}', props.color),
        props.block ? ui.value.block : ui.value.inline
      ), props.class)
    })

    const leadingIconName = computed(() => {
      if (props.loading) {
        return props.loadingIcon
      }

      return props.leadingIcon || props.icon
    })

    const trailingIconName = computed(() => {
      if (props.loading && !isLeading.value) {
        return props.loadingIcon
      }

      return props.trailingIcon || props.icon
    })

    const leadingIconClass = computed(() => {
      return twJoin(
        ui.value.icon.base,
        ui.value.icon.size[size.value],
        props.loading && ui.value.icon.loading
      )
    })

    const trailingIconClass = computed(() => {
      return twJoin(
        ui.value.icon.base,
        ui.value.icon.size[size.value],
        props.loading && !isLeading.value && ui.value.icon.loading
      )
    })

    return {
      // eslint-disable-next-line vue/no-dupe-keys
      ui,
      attrs,
      isLeading,
      isTrailing,
      isSquare,
      buttonClass,
      leadingIconName,
      trailingIconName,
      leadingIconClass,
      trailingIconClass
    }
  }
})
</script>
