// src/lib/components/layouts/divider/divider.svelte
<script lang="ts">
	import { twMerge, twJoin } from 'tailwind-merge';
	import { UIcon } from '$lib/index.js';
	import { UAvatar } from '$lib/index.js';
	import { css } from './styles.js';
	import type { Size } from '$lib/types/index.js';
	import { ui } from '$lib/ui.config.js';

	export let label: string | null = null;
	export let icon: string | null = null;
	export let avatar: string | null = null;
	export let size: Size = ui.size;
	export let orientation: 'horizontal' | 'vertical' = 'horizontal';
	export let type: 'solid' | 'dotted' | 'dashed' = 'solid';
	export let classProp: any = '';

	$: wrapperClass = twMerge(twJoin(css.wrapper.base, css.wrapper[orientation]), classProp);

	$: containerClass = twJoin(css.container.base, css.container[orientation]);

	$: borderClass = twJoin(
		css.border.base,
		css.border[orientation],
		css.border.size[orientation][size],
		css.border.type[type]
	);
</script>

<div class={wrapperClass} {...$$restProps}>
	<div class={borderClass} />
	{#if label || icon || avatar}
		<div class={containerClass}>
			{#if label}
				<span class={css.label}>
					{label}
				</span>
			{:else if icon}
				<UIcon name={icon} class={css.icon.base} />
			{:else if avatar}
				<UAvatar class={css.avatar} />
			{/if}
		</div>
	{/if}
	<div class={borderClass} />
</div>

// src/runtime/components/layout/divider/Divider.vue
<template>
  <div :class="wrapperClass" v-bind="attrs">
    <div :class="borderClass" />

    <template v-if="label || icon || avatar || $slots.default">
      <div :class="containerClass">
        <slot>
          <span v-if="label" :class="ui.label">
            {{ label }}
          </span>
          <UIcon v-else-if="icon" :name="icon" :class="ui.icon.base" />
          <UAvatar v-else-if="avatar" v-bind="{ size: ui.avatar.size, ...avatar }" :class="ui.avatar.base" />
        </slot>
      </div>

      <div :class="borderClass" />
    </template>
  </div>
</template>

<script lang="ts">
import { toRef, computed, defineComponent } from 'vue'
import type { PropType } from 'vue'
import { twMerge, twJoin } from 'tailwind-merge'
import UIcon from '../elements/Icon.vue'
import UAvatar from '../elements/Avatar.vue'
import { useUI } from '../../../composables/useUI'
import { mergeConfig } from '../../../utils'
import type { Avatar, Strategy } from '../../../types'
// @ts-expect-error
import appConfig from '#build/app.config'
import { divider } from '#ui/ui.config'

const config = mergeConfig<typeof divider>(appConfig.ui.strategy, appConfig.ui.divider, divider)

export default defineComponent({
  components: {
    UIcon,
    UAvatar
  },
  inheritAttrs: false,
  props: {
    label: {
      type: String,
      default: null
    },
    icon: {
      type: String,
      default: null
    },
    avatar: {
      type: Object as PropType<Avatar>,
      default: null
    },
    orientation: {
      type: String as PropType<'horizontal' | 'vertical'>,
      default: 'horizontal',
      validator: (value: string) => ['horizontal', 'vertical'].includes(value)
    },
    type: {
      type: String as PropType<'solid' | 'dotted' | 'dashed'>,
      default: 'solid',
      validator: (value: string) => ['solid', 'dotted', 'dashed'].includes(value)
    },
    class: {
      type: [String, Object, Array] as PropType<any>,
      default: () => ''
    },
    ui: {
      type: Object as PropType<Partial<typeof config> & { strategy?: Strategy }>,
      default: () => ({})
    }
  },
  setup (props) {
    const { ui, attrs } = useUI('divider', toRef(props, 'ui'), config)

    const isHorizontal = computed(() => props.orientation === 'horizontal' )

    const wrapperClass = computed(() => {
      return twMerge(twJoin(
        ui.value.wrapper.base,
        isHorizontal.value ? ui.value.wrapper.horizontal : ui.value.wrapper.vertical
      ), props.class)
    })

    const containerClass = computed(() => {
      return twJoin(
        ui.value.container.base,
        isHorizontal.value ? ui.value.container.horizontal : ui.value.container.vertical
      )
    })

    const borderClass = computed(() => {
      return twJoin(
        ui.value.border.base,
        isHorizontal.value ? ui.value.border.horizontal : ui.value.border.vertical,
        isHorizontal.value ? ui.value.border.size.horizontal : ui.value.border.size.vertical,
        ui.value.border.type[props.type]
      )
    })

    return {
      // eslint-disable-next-line vue/no-dupe-keys
      ui,
      attrs,
      wrapperClass,
      containerClass,
      borderClass
    }
  }
})
</script>
